In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd

In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive

In [ ]:
ruta="/content/drive/My Drive/progra/datanueva.csv"

In [ ]:
datos=pd.read_csv(ruta)
datos.head()

,Series_Title,ID,Poster_Link,Released_Year,Certificate,Runtime,Genre,IMDB_Rating,Overview,Meta_score,Director,Star1,Star2,Star3,Star4,No_of_Votes,Gross
0,The Shawshank Redemption,1,https://m.media-amazon.com/images/M/MV5BMDFkYT...,1994,A,142 min,Drama,9.3,Two imprisoned men bond over a number of years...,80.0,Frank Darabont,Tim Robbins,Morgan Freeman,Bob Gunton,William Sadler,2343110,"28,341,469"
1,The Godfather,2,https://m.media-amazon.com/images/M/MV5BM2MyNj...,1972,A,175 min,"Crime, Drama",9.2,An organized crime dynasty's aging patriarch t...,100.0,Francis Ford Coppola,Marlon Brando,Al Pacino,James Caan,Diane Keaton,1620367,"134,966,411"
2,The Dark Knight,3,https://m.media-amazon.com/images/M/MV5BMTMxNT...,2008,UA,152 min,"Action, Crime, Drama",9.0,When the menace known as the Joker wreaks havo...,84.0,Christopher Nolan,Christian Bale,Heath Ledger,Aaron Eckhart,Michael Caine,2303232,"534,858,444"
3,The Godfather: Part II,4,https://m.media-amazon.com/images/M/MV5BMWMwMG...,1974,A,202 min,"Crime, Drama",9.0,The early life and career of Vito Corleone in ...,90.0,Francis Ford Coppola,Al Pacino,Robert De Niro,Robert Duvall,Diane Keaton,1129952,"57,300,000"
4,12 Angry Men,5,https://m.media-amazon.com/images/M/MV5BMWU4N2...,1957,U,96 min,"Crime, Drama",9.0,A jury holdout attempts to prevent a miscarria...,96.0,Sidney Lumet,Henry Fonda,Lee J. Cobb,Martin Balsam,John Fiedler,689845,"4,360,000"

In [ ]:
print(f"datos{datos.shape}")

datos(1000, 17)

In [ ]:
datos.describe()

                ID  IMDB_Rating  Meta_score   No_of_Votes
count  1000.000000  1000.000000  843.000000  1.000000e+03
mean    500.500000     7.949300   77.971530  2.736929e+05
std     288.819436     0.275491   12.376099  3.273727e+05
min       1.000000     7.600000   28.000000  2.508800e+04
25%     250.750000     7.700000   70.000000  5.552625e+04
50%     500.500000     7.900000   79.000000  1.385485e+05
75%     750.250000     8.100000   87.000000  3.741612e+05
max    1000.000000     9.300000  100.000000  2.343110e+06

In [ ]:
datos.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1000 entries, 0 to 999
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   1000 non-null   object
 1   ID             1000 non-null   int64
 2   Poster_Link    1000 non-null   object
 3   Released_Year  1000 non-null   object
 4   Certificate    899 non-null    object
 5   Runtime        1000 non-null   object
 6   Genre          1000 non-null   object
 7   IMDB_Rating    1000 non-null   float64
 8   Overview       1000 non-null   object
 9   Meta_score     843 non-null    float64
 10  Director       1000 non-null   object
 11  Star1          1000 non-null   object
 12  Star2          1000 non-null   object
 13  Star3          1000 non-null   object
 14  Star4          1000 non-null   object
 15  No_of_Votes    1000 non-null   int64
 16  Gross          831 non-null    object
dtypes: float64(2), int64(2), object(13)
memory usage: 132.9+ KB

identificacion de columnas nulas

In [ ]:
columnasnulas=datos.isnull().any()
columnasnulas

Series_Title     False
ID               False
Poster_Link      False
Released_Year    False
Certificate       True
Runtime          False
Genre            False
IMDB_Rating      False
Overview         False
Meta_score        True
Director         False
Star1            False
Star2            False
Star3            False
Star4            False
No_of_Votes      False
Gross             True
dtype: bool

identificando filas nulas

In [ ]:
filas_nulas= datos[datos.isnull().any(axis=1)]
print(filas_nulas)

               Series_Title    ID  \
18                 Hamilton    19
20          Soorarai Pottru    21
30                  Seppuku    31
32    It's a Wonderful Life    33
46           Hotaru no haka    47
..                      ...   ...
993                  Blowup   994
995  Breakfast at Tiffany's   996
996                   Giant   997
998                Lifeboat   999
999            The 39 Steps  1000

                                           Poster_Link Released_Year  \
18   https://m.media-amazon.com/images/M/MV5BNjViNW...          2020
20   https://m.media-amazon.com/images/M/MV5BOTc2ZT...          2020
30   https://m.media-amazon.com/images/M/MV5BYjBmYT...          1962
32   https://m.media-amazon.com/images/M/MV5BZjc4ND...          1946
46   https://m.media-amazon.com/images/M/MV5BZmY2Nj...          1988
..                                                 ...           ...
993  https://m.media-amazon.com/images/M/MV5BYTE4YW...          1966
995  https://m.media-amazon.com/images/M/MV5BNGEwMT...          1961
996  https://m.media-amazon.com/images/M/MV5BODk3Yj...          1956
998  https://m.media-amazon.com/images/M/MV5BZTBmMj...          1944
999  https://m.media-amazon.com/images/M/MV5BMTY5OD...          1935

    Certificate  Runtime                      Genre  IMDB_Rating  \
18        PG-13  160 min  Biography, Drama, History          8.6
20            U  153 min                      Drama          8.6
30          NaN  133 min     Action, Drama, Mystery          8.6
32           PG  130 min     Drama, Family, Fantasy          8.6
46            U   89 min      Animation, Drama, War          8.5
..          ...      ...                        ...          ...
993           A  111 min   Drama, Mystery, Thriller          7.6
995           A  115 min     Comedy, Drama, Romance          7.6
996           G  201 min             Drama, Western          7.6
998         NaN   97 min                 Drama, War          7.6
999         NaN   86 min   Crime, Mystery, Thriller          7.6

                                              Overview  Meta_score  \
18   The real life of one of America's foremost fou...        90.0
20   Nedumaaran Rajangam "Maara" sets out to make t...         NaN
30   When a ronin requesting seppuku at a feudal lo...        85.0
32   An angel is sent from Heaven to help a despera...        89.0
46   A young boy and his little sister struggle to ...        94.0
..                                                 ...         ...
993  A fashion photographer unknowingly captures a ...        82.0
995  A young New York socialite becomes interested ...        76.0
996  Sprawling epic covering the life of a Texas ca...        84.0
998  Several survivors of a torpedoed merchant ship...        78.0
999  A man in London tries to help a counter-espion...        93.0

                   Director               Star1              Star2  \
18              Thomas Kail  Lin-Manuel Miranda       Phillipa Soo
20            Sudha Kongara              Suriya           Madhavan
30         Masaki Kobayashi     Tatsuya Nakadai     Akira Ishihama
32              Frank Capra       James Stewart         Donna Reed
46            Isao Takahata     Tsutomu Tatsumi    Ayano Shiraishi
..                      ...                 ...                ...
993  Michelangelo Antonioni      David Hemmings   Vanessa Redgrave
995           Blake Edwards      Audrey Hepburn     George Peppard
996          George Stevens    Elizabeth Taylor        Rock Hudson
998        Alfred Hitchcock   Tallulah Bankhead        John Hodiak
999        Alfred Hitchcock        Robert Donat  Madeleine Carroll

                Star3                   Star4  No_of_Votes Gross
18    Leslie Odom Jr.  Renée Elise Goldsberry        55291   NaN
20       Paresh Rawal       Aparna Balamurali        54995   NaN
30     Shima Iwashita           Tetsurô Tanba        42004   NaN
32   Lionel Barrymore         Thomas Mitchell       405801   NaN
46    Akemi Yamaguchi       Yoshiko Shinohara       235231   NaN
..                ...                     ...          ...   ...
993       Sarah Miles             John Castle        56513   NaN
995     Patricia Neal             Buddy Ebsen       166544   NaN
996        James Dean           Carroll Baker        34075   NaN
998     Walter Slezak          William Bendix        26471   NaN
999    Lucie Mannheim          Godfrey Tearle        51853   NaN

[286 rows x 17 columns]

In [ ]:
####eliminando filas nulas ####

data_sin_nulos= datos.dropna()
data_sin_nulos.info()

<class 'pandas.core.frame.DataFrame'>
Index: 714 entries, 0 to 997
Data columns (total 17 columns):
 #   Column         Non-Null Count  Dtype
---  ------         --------------  -----
 0   Series_Title   714 non-null    object
 1   ID             714 non-null    int64
 2   Poster_Link    714 non-null    object
 3   Released_Year  714 non-null    object
 4   Certificate    714 non-null    object
 5   Runtime        714 non-null    object
 6   Genre          714 non-null    object
 7   IMDB_Rating    714 non-null    float64
 8   Overview       714 non-null    object
 9   Meta_score     714 non-null    float64
 10  Director       714 non-null    object
 11  Star1          714 non-null    object
 12  Star2          714 non-null    object
 13  Star3          714 non-null    object
 14  Star4          714 non-null    object
 15  No_of_Votes    714 non-null    int64
 16  Gross          714 non-null    object
dtypes: float64(2), int64(2), object(13)
memory usage: 100.4+ KB

eliminando filas

In [ ]:
nulos_Meta_score=datos[datos["Meta_score"].isnull()]
print(nulos_Meta_score)

                      Series_Title   ID  \
20                 Soorarai Pottru   21
54       Ayla: The Daughter of War   55
55                    Vikram Vedha   56
57                          Dangal   58
65                Taare Zameen Par   66
..                             ...  ...
872  The Day the Earth Stood Still  873
874                          Gilda  875
899                      El cuerpo  900
909                      Celda 211  910
913                      Die Welle  914

                                           Poster_Link Released_Year  \
20   https://m.media-amazon.com/images/M/MV5BOTc2ZT...          2020
54   https://m.media-amazon.com/images/M/MV5BNWJhMD...          2017
55   https://m.media-amazon.com/images/M/MV5BY2FiMT...          2017
57   https://m.media-amazon.com/images/M/MV5BMTQ4Mz...          2016
65   https://m.media-amazon.com/images/M/MV5BMDhjZW...          2007
..                                                 ...           ...
872  https://m.media-amazon.com/images/M/MV5BMTU5NT...          1951
874  https://m.media-amazon.com/images/M/MV5BYWUxMz...          1946
899  https://m.media-amazon.com/images/M/MV5BNGMxZj...          2012
909  https://m.media-amazon.com/images/M/MV5BMjI2OD...          2009
913  https://m.media-amazon.com/images/M/MV5BMzc0Zm...          2008

    Certificate  Runtime                      Genre  IMDB_Rating  \
20            U  153 min                      Drama          8.6
54          NaN  125 min  Biography, Drama, History          8.4
55           UA  147 min       Action, Crime, Drama          8.4
57            U  161 min   Action, Biography, Drama          8.4
65            U  165 min              Drama, Family          8.4
..          ...      ...                        ...          ...
872           U   92 min              Drama, Sci-Fi          7.7
874    Approved  110 min  Drama, Film-Noir, Romance          7.7
899         NaN  112 min          Mystery, Thriller          7.6
909         NaN  113 min   Action, Adventure, Crime          7.6
913         NaN  107 min            Drama, Thriller          7.6

                                              Overview  Meta_score  \
20   Nedumaaran Rajangam "Maara" sets out to make t...         NaN
54   In 1950, amid-st the ravages of the Korean War...         NaN
55   Vikram, a no-nonsense police officer, accompan...         NaN
57   Former wrestler Mahavir Singh Phogat and his t...         NaN
65   An eight-year-old boy is thought to be a lazy ...         NaN
..                                                 ...         ...
872  An alien lands and tells the people of Earth t...         NaN
874  A small-time gambler hired to work in a Buenos...         NaN
899  A detective searches for the body of a femme f...         NaN
909  The story of two men on different sides of a p...         NaN
913  A high school teacher's experiment to demonstr...         NaN

          Director           Star1            Star2               Star3  \
20   Sudha Kongara          Suriya         Madhavan        Paresh Rawal
54       Can Ulkay       Erdem Can   Çetin Tekindor     Ismail Hacioglu
55         Gayatri         Pushkar         Madhavan    Vijay Sethupathi
57   Nitesh Tiwari      Aamir Khan    Sakshi Tanwar  Fatima Sana Shaikh
65      Aamir Khan     Amole Gupte  Darsheel Safary          Aamir Khan
..             ...             ...              ...                 ...
872    Robert Wise  Michael Rennie    Patricia Neal        Hugh Marlowe
874  Charles Vidor   Rita Hayworth       Glenn Ford     George Macready
899    Oriol Paulo   Jose Coronado       Hugo Silva         Belén Rueda
909  Daniel Monzón      Luis Tosar   Alberto Ammann     Antonio Resines
913  Dennis Gansel    Jürgen Vogel    Frederick Lau         Max Riemelt

                 Star4  No_of_Votes       Gross
20   Aparna Balamurali        54995         NaN
54       Kyung-jin Lee        34112         NaN
55    Shraddha Srinath        28401         NaN
57      Sanya Malhotra       156479  12,391,761
65        Tisca Chopra       168895   1,223,869
..                 ...          ...         ...
872          Sam Jaffe        76315         NaN
874     Joseph Calleia        27991         NaN
899       Aura Garrido        57549         NaN
909       Manuel Morón        63882         NaN
913    Jennifer Ulrich       102742         NaN

[157 rows x 17 columns]